repositories_refactors_script:
	clear; time python3 repository_refactors.py

metrics_evolution_refactors_script:
	clear; time python3 metrics_evolution_refactors.py

dependencies:
	pip install
	pip install colorama
	pip install pandas
	pip install pydriller
	pip install scikit-learn
	pip install tqdm
