ck_metrics:
	clear; python3 ck_metrics.py

metrics_evolution:
	clear; python3 metrics_evolution.py

metrics_statistics:
	clear; python3 metrics_statistics.py

generate_images:
clear; python3 generate_images.py

top_changes:
	clear; python3 top_changes.py

dependencies:
	pip install matplotlib
	pip install numpy
	pip install pandas
	pip install pydriller
	pip install tqdm