# Main Scripts:

ck_metrics_script:
	clear; python3 ck_metrics.py

repository_diffs_script:
	clear; python3 repository_diffs.py

generate_images_script:
	clear; python3 generate_images.py

metrics_changes_script:
	clear; python3 metrics_changes.py

# Auxiliar Scripts:

empty_folders_script:
	chmod +x Scripts/empty_folders.py; clear; python3 Scripts/empty_folders.py

extractZipFiles:
	chmod +x Scripts/extractZipFiles.py; clear; python3 Scripts/extractZipFiles.py

generateZipFiles:
	chmod +x Scripts/generateZipFiles.py; clear; python3 Scripts/generateZipFiles.py

moveExtractedFiles:
	chmod +x Scripts/moveExtractedFiles.py; clear; python3 Scripts/moveExtractedFiles.py
	
# Install Dependencies:

dependencies:
	pip install matplotlib
	pip install numpy
	pip install pandas
	pip install pydriller
	pip install scikit-learn
	pip install tqdm