ck_metrics_script:
	clear; python3 ck_metrics.py

generate_images_script:
	clear; python3 generate_images.py

metrics_changes_script:
	clear; python3 metrics_changes.py

dependencies:
	pip install matplotlib
	pip install numpy
	pip install pandas
	pip install pydriller
	pip install tqdm