name: Update CK Submodule

on:
  schedule:
    # Runs at the start of every hour
    - cron: '0 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-submodule:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          # Fetches all history for all tags and branches, including submodules
          fetch-depth: 0
          submodules: 'recursive'

      - name: Configure git settings
        run: |
          git config --global pull.rebase false
          git config --global user.email "breno.vicio78@gmail.com"
          git config --global user.name "Breno Farias da Silva"

      - name: Forcefully update CK submodule to latest FEAT-ClassMetric branch
        run: |
          cd ck
          git fetch origin FEAT-ClassMetric
          git checkout FEAT-ClassMetric
          git reset --hard origin/FEAT-ClassMetric

      - name: Return to main repository and check for changes
        run: |
          cd ..
          git add ck
          git diff --cached --quiet || git commit -m "UPDATE: Automatically updated CK submodule to the latest version on FEAT-ClassMetric branch."

      - name: Push changes if any
        run: |
          git push origin main || echo "No changes to push."
