name: Update Worked-Example-Miner-Candidates Submodule

on:
  schedule:
    # Runs at the start of every hour
    - cron: '0 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-submodule:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          # Fetches all history for all tags and branches, including submodules
          fetch-depth: 0
          submodules: 'recursive'

      - name: Configure git settings
        run: |
          git config --global pull.rebase false
          git config --global user.email "breno.vicio78@gmail.com"
          git config --global user.name "Breno Farias da Silva"

      - name: Fetch all branches
        run: |
          git fetch --all

      - name: Update Worked-Example-Miner-Candidates submodule on all branches
        run: |
          for branch in $(git branch -r | grep -v '\->' | sed 's/origin\///'); do
            git checkout $branch
            cd Worked-Example-Miner-Candidates
            git fetch origin main
            git checkout main
            git reset --hard origin/main
            cd ..
            git add Worked-Example-Miner-Candidates
            git diff --cached --quiet || git commit -m "UPDATE: Updated Worked-Example-Miner-Candidates submodule on branch $branch."
            git push origin $branch || echo "No changes to push on branch $branch."
          done
